spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://101.132.181.50:3306/gulimall_pms?characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 101.132.181.50:8848
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 10001
logging:
  level:
    com.atguigu.gulimall: debug
